=== verogmayo/107ProyectoDAW/107LMSGIProyectoLMGSI/ud4/03/03.dtd
<!ELEMENT programmingLanguages (language+)>
<!ELEMENT language (description, example)>
<!ATTLIST language name CDATA #REQUIRED>
<!ELEMENT description (#PCDATA)>
<!ELEMENT example (#PCDATA)>
<!ATTLIST programmingLanguages xmlns:xsi CDATA #IMPLIED>
<!ATTLIST xsi:noNamespaceSchemaLocation  xmlns:xsi CDATA #IMPLIED>

=== verogmayo/107ProyectoDAW/107LMSGIProyectoLMGSI/ud4/03/03.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/css" href="css/estilos.css"?>
<programmingLanguages xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="03.xsd"></programmingLanguages>
<!DOCTYPE programmingLanguages SYSTEM '03.dtd'>
<programmingLanguages>
    <language name="Python">
        <description>
            Python es un lenguaje de programacion interpretado, de alto nivel y de propósito general.
        </description>
        <example>
<![CDATA[ 
def saludos():
    print("¡Hola, Mundo!")
                
saludo()  ]]>
        </example>
    </language>
    <language name="JavaScript">
        <description>
            JavaScript es un lenguaje de programación que se utiliza para crear contenido dinámico en la web.
        </description>
        <example>
<![CDATA[ 
function saludo() {
    alert("¡Hola, Mundo!");
}

saludo(); ]]>
        </example>
    </language>
    <language name="Java">
        <description>
           Java es un lenguaje de programación de propósito general que es ampliamente utilizado en aplicaciones empresariales y móviles.
        </description>
        <example>
<![CDATA[ 
public class Saludo {
    public static void main(String[] args) {
        System.out.println("¡Hola, Mundo!");
    }
} ]]>
        </example>
    </language>
    <language name="C++">
        <description>
            C++ es un lenguaje de programación de propósito general, conocido por su eficiencia y uso en aplicaciones de alto rendimiento.
        </description>
        <example>
<![CDATA[ 
#include <iostream>
using namespace std;

int main() {
    cout << "¡Hola, Mundo!" << endl;
    return 0;
} ]]>
        </example>
    </language>
    <language name="Ruby">
        <description>
            Ruby es un lenguaje de programación dinámico y de alto nivel, conocido por su sintaxis simple y elegante.
        </description>
        <example>
<![CDATA[ 
def saludo
     puts "¡Hola, Mundo!"
   end

   saludo ]]>
        </example>
    </language>
</programmingLanguages>
