=== verogmayo/107ProyectoDAW/107LMSGIProyectoLMGSI/examen/02/xml/libro.dtd
<!ELEMENT juegos (libro)>
<!ELEMENT libro (titulo,autores,anio)>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT autores (autor+)>
<!ELEMENT autor (nombre, apellido, nacionalidad)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellido (#PCDATA)>
<!ELEMENT nacionalidad (#PCDATA)>
<!ELEMENT anio (#PCDATA)>
<!ATTLIST libro genero CDATA #IMPLIED>

=== verogmayo/107ProyectoDAW/107LMSGIProyectoLMGSI/examen/02/xml/libro.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE juegos SYSTEM 'libro.dtd'>
<juegos>
    <libro genero="ciencia ficcion,aventura,juvenil" >
        <titulo>
        The Hunger games
        </titulo>
        <autores>
            <autor>
                <nombre>Suzanne </nombre>
                <apellido>Collins</apellido>
                <nacionalidad>Estadounidense</nacionalidad>
            </autor>
        </autores>
        <anio>2008</anio>
    </libro>
</juegos>
