=== verogmayo/107ProyectoDAW/107LMSGIProyectoLMGSI/ud4/02/02.dtd
<!ELEMENT biblioteca (libro)+>
<!ELEMENT libro (titulo,autores,anio)>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT autores (autor+)>
<!ELEMENT autor (nombre, apellido, nacionalidad)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellido (#PCDATA)>
<!ELEMENT nacionalidad (#PCDATA)>
<!ELEMENT anio (#PCDATA)>
<!ATTLIST libro idlibro ID #REQUIRED>
<!ATTLIST libro genero CDATA #IMPLIED>
<!ATTLIST libro idioma CDATA "EspaÃ±ol">
<!ATTLIST libro formato (impreso|digital) "impreso">
<!ATTLIST libro ref IDREFS #IMPLIED>

=== verogmayo/107ProyectoDAW/107LMSGIProyectoLMGSI/ud4/02/02.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE biblioteca SYSTEM '02.dtd'>
<biblioteca>
    <libro idlibro="libro1" genero="novela" ref="libro2">
        <titulo>
        puntos para los locos
        </titulo>
        <autores>
            <autor>
                <nombre>Angel </nombre>
                <apellido>Martín</apellido>
                <nacionalidad>Español</nacionalidad>
            </autor>
        </autores>
        <anio>2024</anio>
    </libro>
    <libro idlibro="libro2" genero="novela">
        <titulo>
        Por si las voces vuelven
        </titulo>
        <autores>
            <autor>
                <nombre>Angel </nombre>
                <apellido>Martín</apellido>
                <nacionalidad>Español</nacionalidad>
            </autor>
        </autores>
        <anio>2020</anio>
    </libro>
</biblioteca>
